services:
  mysql:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: devdojo
      MYSQL_USER: patrick
      MYSQL_PASSWORD: academy
    ports:
      - "3306:3306"
    volumes:
      - devdojo-db:/var/lib/mysql

volumes:
  devdojo-db: