spring:
#  security:
#    user:
#      name: user
#      password: devdojo
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER:root}
    password: ${ENV_ROOT_PASSWORD:devdojo}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
  flyway:
    enabled: true

logging:
  level:
    academy.devdojo: debug
#    org.hibernate.orm.jdbc.bind: trace
#    net.ttddyy.dsproxy.listener: debug
    org.springframework.security: debug

server:
  port: 8090
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
    include-binding-errors: always
    include-message: always
  tomcat:
    threads:
      max: 20

brasil-api:
  base-url: ${BRASIL_API_BASE_URL:https://brasilapi.com.br/api}
  cep-uri: ${BRASIL_API_URI:/cep/v1/{cep}}